# Generated by Django 2.1.5 on 2020-10-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='track_clicks',
            field=models.BooleanField(default=False, verbose_name='track clicks'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='track_opens',
            field=models.BooleanField(default=False, verbose_name='track opens'),
        ),
    ]
